### ISSUE TITLE
Feature Request: Highlight CIDR Notation

### ISSUE THREAD

**Issue by seajaysec** [medo64/Highlight-IP#1]
I love this plugin, and wanted to thank you for your work on it.

Would be open to considering a highlight of not just the IP address, but the CIDR notation as well? Highlighting `/24` or `/` whatever in a different color than the IP would be really great for my use case.

**Comment by medo64** [comment]
Partially added in 1.1.0.

Subnet mask, if detected, is highlighted together with IP address. I will look into allowing different colors for for prefix/subnet part.

**Comment by medo64** [comment]
This has been implemented in 1.2.0. Now you can use standard VSCode color customizations to set it up.

    "workbench.colorCustomizations": {
        "ipaddress.network": "#ff0000",
        "ipaddress.subnet": "#00ff00",
    }
